spring:
  datasource-cms:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/CMS?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: abcd1234!
  datasource-user:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/USER?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: abcd1234!
  sql:
    init:
      mode: always # schema.sql, data.sql 스크립트 실행 설정(ALWAYS, EMBDDED, NEVER)
  jpa:
    hibernate:
#      ddl-auto: create # multi datasource 인경우 데이터베이스마다 사용전략이 다르기때문에 설정이 안됨
      hbm2ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # 지연 로딩 성능 최적화를 위해 사용(in 쿼리 개수 설정 100 ~ 1000 권장)
    defer-datasource-initialization: true
  data:
    web:
      pageable:
        default-page-size: 10 # 기본 페이지 사이즈 20

logging.level:
  org.hibernate.SQL: info
#  org.hibernate.type: trace

# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용 (아래 명령어를 터미널에 쳐보면 그대로 나옴)
# $ echo 'spring-boot-security-jwt-tutorial-spring-boot-security-jwt-tutorial-cms' | base64
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLXNwcmluZy1ib290LXNlY3VyaXR5LWp3dC10dXRvcmlhbC1jbXMK