-- 권한 등록
INSERT INTO AUTHORITY (AUTHORITY, AUTHORITY_NAME, AUTHORITY_TYPE, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('ROLE_ADMIN', '최고관리자', 'MANAGER', 'admin', 'admin', NOW(), NOW());
INSERT INTO AUTHORITY (AUTHORITY, AUTHORITY_NAME, AUTHORITY_TYPE, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('ROLE_MANAGER', '관리자', 'MANAGER', 'admin', 'admin', NOW(), NOW());
INSERT INTO AUTHORITY (AUTHORITY, AUTHORITY_NAME, AUTHORITY_TYPE, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('ROLE_USER_1', '권한1', 'MEMBER', 'admin', 'admin', NOW(), NOW());
INSERT INTO AUTHORITY (AUTHORITY, AUTHORITY_NAME, AUTHORITY_TYPE, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('ROLE_USER_2', '권한2', 'MEMBER', 'admin', 'admin', NOW(), NOW());
INSERT INTO AUTHORITY (AUTHORITY, AUTHORITY_NAME, AUTHORITY_TYPE, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('ROLE_USER_3', '권한3', 'MEMBER', 'admin', 'admin', NOW(), NOW());

-- 관리자 등록(비번 1234)
INSERT INTO MANAGER (USERNAME, PASSWORD, NAME, EMAIL, HP, STATUS, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('admin', '$2a$10$is4cfHcYBgNPhcTMW2e8c.gd0EdqYShhhicWddNX28zfQUQkDJrq2', '최고관리자', 'admin@naver.com', '010-1111-2222', 'ACTIVITY', 'admin', 'admin', NOW(), NOW());
INSERT INTO MANAGER (USERNAME, PASSWORD, NAME, EMAIL, HP, STATUS, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('manager', '$2a$10$is4cfHcYBgNPhcTMW2e8c.gd0EdqYShhhicWddNX28zfQUQkDJrq2', '관리자', 'manager@naver.com', '010-1234-5678', 'ACTIVITY', 'admin', 'admin', NOW(), NOW());

-- 관리자 권한 등록
INSERT INTO MANAGER_AUTHORITY (MANAGER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO MANAGER_AUTHORITY (MANAGER_ID, AUTHORITY_ID) VALUES (2, 2);

-- 회원 등록(비번 1234)
INSERT INTO MEMBER (NAME, PASSWORD, EMAIL, HP, STATUS, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('회원1', '$2a$10$is4cfHcYBgNPhcTMW2e8c.gd0EdqYShhhicWddNX28zfQUQkDJrq2', 'member1@naver.com', '010-1111-2222', 'ACTIVITY', 'member1@naver.com', 'member1@naver.com', NOW(), NOW());
INSERT INTO MEMBER (NAME, PASSWORD, EMAIL, HP, STATUS, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('회원2', '$2a$10$is4cfHcYBgNPhcTMW2e8c.gd0EdqYShhhicWddNX28zfQUQkDJrq2', 'member2@naver.com', '010-1234-5678', 'ACTIVITY', 'member2@naver.com', 'member2@naver.com', NOW(), NOW());
INSERT INTO MEMBER (NAME, PASSWORD, EMAIL, HP, STATUS, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('회원3', '$2a$10$is4cfHcYBgNPhcTMW2e8c.gd0EdqYShhhicWddNX28zfQUQkDJrq2', 'member3@naver.com', '010-1234-5678', 'ACTIVITY', 'member3@naver.com', 'member3@naver.com', NOW(), NOW());
INSERT INTO MEMBER (NAME, PASSWORD, EMAIL, HP, STATUS, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('회원4', '$2a$10$is4cfHcYBgNPhcTMW2e8c.gd0EdqYShhhicWddNX28zfQUQkDJrq2', 'member4@naver.com', '010-1234-5678', 'ACTIVITY', 'member4@naver.com', 'member4@naver.com', NOW(), NOW());
INSERT INTO MEMBER (NAME, PASSWORD, EMAIL, HP, STATUS, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('회원5', '$2a$10$is4cfHcYBgNPhcTMW2e8c.gd0EdqYShhhicWddNX28zfQUQkDJrq2', 'member5@naver.com', '010-1234-5678', 'ACTIVITY', 'member5@naver.com', 'member5@naver.com', NOW(), NOW());
INSERT INTO MEMBER (NAME, PASSWORD, EMAIL, HP, STATUS, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('회원6', '$2a$10$is4cfHcYBgNPhcTMW2e8c.gd0EdqYShhhicWddNX28zfQUQkDJrq2', 'member6@naver.com', '010-1234-5678', 'ACTIVITY', 'member6@naver.com', 'member6@naver.com', NOW(), NOW());
INSERT INTO MEMBER (NAME, PASSWORD, EMAIL, HP, STATUS, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('회원7', '$2a$10$is4cfHcYBgNPhcTMW2e8c.gd0EdqYShhhicWddNX28zfQUQkDJrq2', 'member7@naver.com', '010-1234-5678', 'ACTIVITY', 'member7@naver.com', 'member7@naver.com', NOW(), NOW());
INSERT INTO MEMBER (NAME, PASSWORD, EMAIL, HP, STATUS, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('회원8', '$2a$10$is4cfHcYBgNPhcTMW2e8c.gd0EdqYShhhicWddNX28zfQUQkDJrq2', 'member8@naver.com', '010-1234-5678', 'ACTIVITY', 'member8@naver.com', 'member8@naver.com', NOW(), NOW());
INSERT INTO MEMBER (NAME, PASSWORD, EMAIL, HP, STATUS, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('회원9', '$2a$10$is4cfHcYBgNPhcTMW2e8c.gd0EdqYShhhicWddNX28zfQUQkDJrq2', 'member9@naver.com', '010-1234-5678', 'ACTIVITY', 'member9@naver.com', 'member9@naver.com', NOW(), NOW());
INSERT INTO MEMBER (NAME, PASSWORD, EMAIL, HP, STATUS, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('회원10', '$2a$10$is4cfHcYBgNPhcTMW2e8c.gd0EdqYShhhicWddNX28zfQUQkDJrq2', 'member10@naver.com', '010-1234-5678', 'ACTIVITY', 'member10@naver.com', 'member10@naver.com', NOW(), NOW());

-- 회원 권한 등록
INSERT INTO MEMBER_AUTHORITY (MEMBER_ID, AUTHORITY_ID) VALUES (1, 3);
INSERT INTO MEMBER_AUTHORITY (MEMBER_ID, AUTHORITY_ID) VALUES (2, 4);
INSERT INTO MEMBER_AUTHORITY (MEMBER_ID, AUTHORITY_ID) VALUES (3, 5);
INSERT INTO MEMBER_AUTHORITY (MEMBER_ID, AUTHORITY_ID) VALUES (4, 3);
INSERT INTO MEMBER_AUTHORITY (MEMBER_ID, AUTHORITY_ID) VALUES (5, 4);
INSERT INTO MEMBER_AUTHORITY (MEMBER_ID, AUTHORITY_ID) VALUES (6, 5);
INSERT INTO MEMBER_AUTHORITY (MEMBER_ID, AUTHORITY_ID) VALUES (7, 3);
INSERT INTO MEMBER_AUTHORITY (MEMBER_ID, AUTHORITY_ID) VALUES (8, 4);
INSERT INTO MEMBER_AUTHORITY (MEMBER_ID, AUTHORITY_ID) VALUES (9, 5);
INSERT INTO MEMBER_AUTHORITY (MEMBER_ID, AUTHORITY_ID) VALUES (10, 3);
INSERT INTO MEMBER_AUTHORITY (MEMBER_ID, AUTHORITY_ID) VALUES (10, 4);
INSERT INTO MEMBER_AUTHORITY (MEMBER_ID, AUTHORITY_ID) VALUES (10, 5);

-- 게시판 등록
INSERT INTO BOARD_MANAGER (NAME, DESCRIPTION, BOARD_TYPE, BOARD_USE_YN, COMMENT_USE_YN, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('공지사항', '공지사항게시판', 'NOTICE', 'Y', 'Y', 'admin@naver.com', 'admin@naver.com', NOW(), NOW());

-- 테스트 메뉴 등록
INSERT INTO MENU (MENU_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATE_BY, LAST_MODIFIED_BY, DESCRIPTION, LEVEL, MENU_TYPE, NAME, ORD, USE_YN, PARENT_ID, TOP_ID) VALUES (1, NOW(), NOW(), 'admin@naver.com', 'admin@naver.com', '서울소식', 0, 'MENU', '서울소식', 2, 'Y', null, null);
INSERT INTO MENU (MENU_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATE_BY, LAST_MODIFIED_BY, DESCRIPTION, LEVEL, MENU_TYPE, NAME, ORD, USE_YN, PARENT_ID, TOP_ID) VALUES (2, NOW(), NOW(), 'admin@naver.com', 'admin@naver.com', '새소식', 1, 'MENU', '새소식', 1, 'Y', 1, 1);
INSERT INTO MENU (MENU_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATE_BY, LAST_MODIFIED_BY, DESCRIPTION, LEVEL, MENU_TYPE, NAME, ORD, USE_YN, PARENT_ID, TOP_ID) VALUES (3, NOW(), NOW(), 'admin@naver.com', 'admin@naver.com', '서울시 정책 뉴스', 1, 'BOARD', '서울시 정책 뉴스', 2, 'Y', 1, 1);
INSERT INTO MENU (MENU_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATE_BY, LAST_MODIFIED_BY, DESCRIPTION, LEVEL, MENU_TYPE, NAME, ORD, USE_YN, PARENT_ID, TOP_ID) VALUES (4, NOW(), NOW(), 'admin@naver.com', 'admin@naver.com', '보도해명자료', 1, 'BOARD', '보도해명자료', 3, 'Y', 1, 1);

INSERT INTO MENU (MENU_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATE_BY, LAST_MODIFIED_BY, DESCRIPTION, LEVEL, MENU_TYPE, NAME, ORD, USE_YN, PARENT_ID, TOP_ID) VALUES (5, NOW(), NOW(), 'admin@naver.com', 'admin@naver.com', '보도자료', 2, 'BOARD', '보도자료', 1, 'Y', 4, 1);
INSERT INTO MENU (MENU_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATE_BY, LAST_MODIFIED_BY, DESCRIPTION, LEVEL, MENU_TYPE, NAME, ORD, USE_YN, PARENT_ID, TOP_ID) VALUES (6, NOW(), NOW(), 'admin@naver.com', 'admin@naver.com', '해명자료', 2, 'BOARD', '해명자료', 2, 'Y', 4, 1);

INSERT INTO MENU (MENU_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATE_BY, LAST_MODIFIED_BY, DESCRIPTION, LEVEL, MENU_TYPE, NAME, ORD, USE_YN, PARENT_ID, TOP_ID) VALUES (7, NOW(), NOW(), 'admin@naver.com', 'admin@naver.com', '이벤트 신청', 2, 'BOARD', '이벤트 신청', 3, 'Y', 2, 1);
INSERT INTO MENU (MENU_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATE_BY, LAST_MODIFIED_BY, DESCRIPTION, LEVEL, MENU_TYPE, NAME, ORD, USE_YN, PARENT_ID, TOP_ID) VALUES (8, NOW(), NOW(), 'admin@naver.com', 'admin@naver.com', '분야별 새소식', 2, 'BOARD', '분야별 새소식', 1, 'Y', 2, 1);
INSERT INTO MENU (MENU_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATE_BY, LAST_MODIFIED_BY, DESCRIPTION, LEVEL, MENU_TYPE, NAME, ORD, USE_YN, PARENT_ID, TOP_ID) VALUES (9, NOW(), NOW(), 'admin@naver.com', 'admin@naver.com', '이달의 행사 및 축제', 2, 'BOARD', '이달의 행사 및 축제', 2, 'Y', 2, 1);

INSERT INTO MENU (MENU_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATE_BY, LAST_MODIFIED_BY, DESCRIPTION, LEVEL, MENU_TYPE, NAME, ORD, USE_YN, PARENT_ID, TOP_ID) VALUES (10, NOW(), NOW(), 'admin@naver.com', 'admin@naver.com', '시민참여', 0, 'BOARD', '시민참여', 1, 'Y', null, null);
INSERT INTO MENU (MENU_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATE_BY, LAST_MODIFIED_BY, DESCRIPTION, LEVEL, MENU_TYPE, NAME, ORD, USE_YN, PARENT_ID, TOP_ID) VALUES (11, NOW(), NOW(), 'admin@naver.com', 'admin@naver.com', '서울시민과의 대화', 1, 'CONTENTS', '서울시민과의 대화', 1, 'Y', 10, 10);


